abufsrc@Music=outputs=1:map=1[a0],
abufsrc@Ring=outputs=1:map=1[a1],
abufsrc@Alarm=outputs=1:map=1[a2],
abufsrc@Notify=outputs=1:map=1[a3],
abufsrc@TTS=outputs=1:map=1[a4],
abufsrc@Sport=outputs=1:map=1[a5],
abufsrc@Media=outputs=1:map=1[a6],
abufsrc@Enforced=outputs=1:map=1[a7],
[a0][a1][a2][a3][a4][a5][a6][a7]amix=inputs=8:timeout=40:first_input=-1:normalize=0:sample_rate=48000:ch_layout=stereo[mix],
[mix]adevsink@pcm0p=format=nuttx:sample_rate=48000:ch_layout=stereo:devname=/dev/audio/pcm0p;
adevsrc@pcm0c=format=nuttx:devname=/dev/audio/pcm0c:outputs=1:map=1[cap0],
[cap0]abufsink@Capture=inputs=1
